### ISSUE TITLE
Incorrect Error "Invalid Reverse Solidus"

### ISSUE THREAD

**Issue by marcelgerber** [ingorichter/de.richter.brackets.jsonlint#1]
Everytime I edit [en.json in brackets-updates](https://github.com/adobe/brackets-updates/blob/master/updates/stable/en.json) (which passes http://jsonlint.com without errors), I get the message you can see on the screen below by mistake.
![image](https://f.cloud.github.com/assets/2641501/1423095/61e04a44-4005-11e3-9631-eece099d7c75.png)

This may be a mistake in the thirdparty submodule. It seems unicode characters like \u2026 aren't handled properly.

**Comment by marcelgerber** [comment]
@ingorichter This issue is still happening.

**Comment by ingorichter** [comment]
@SAPlayer I've posted an updated version which fixes this error. I used a wrong version of the JSONLint lib. Can you please verify that it works for you? Thanks.

**Comment by marcelgerber** [comment]
Works now. Thank you. Closing.
