### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by czmole** [ingorichter/de.richter.brackets.jsonlint#2]
Hi, Sorry for posting this here, I know its not a bug but couldn't find another way to contact. How to use this plugin ? I thought that is something like helps convert a json into readable form like jsonlint does but with a combination of keys.
Thank you.

**Comment by ingorichter** [comment]
Hi, no problem. The extension will only work inside Brackets. It's main purpose is to provide warnings to the code inspection API in Brackets. If the json is invalid and can't be parsed, error hints will appear in the inspection panel. As I said, this all works in Brackets.

**Comment by czmole** [comment]
Yep, I used it in brackets but I thought it does something else :) Thank you!
