### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by cfjedimaster** [ingorichter/de.richter.brackets.jsonlint#3]
I opened up a JSON file this morning and Brackets is reporting that there is no JSON linter, even though I have this extension installed.

**Comment by cfjedimaster** [comment]
Any word on this? Sorry to bug.

**Comment by cfjedimaster** [comment]
I apologize - this is the issue I had, https://github.com/adobe/brackets/issues/10682.

**Comment by ingorichter** [comment]
No worries. It's great to hear somebody is using it.
